# Generated by Django 2.2 on 2020-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singledmodelorm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='xx@xx.xx', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
    ]
